<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\electricgate\**" />
    <Compile Remove="Systems\Mission\**" />
    <EmbeddedResource Remove="Entities\electricgate\**" />
    <EmbeddedResource Remove="Systems\Mission\**" />
    <None Remove="Entities\electricgate\**" />
    <None Remove="Systems\Mission\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Entities\Turret\Turret.xml" />
    <None Remove="RunABTA.bat" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Entities\Turret\Turret.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="RunABTA.bat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="System.CommandLine" Version="2.0.5" />
	<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Audio.LibOpenMpt\OpenBreed.Audio.LibOpenMpt.csproj" />
    <ProjectReference Include="..\OpenBreed.Common.Game\OpenBreed.Common.Game.csproj" />
    <ProjectReference Include="..\OpenBreed.Common.Tools\OpenBreed.Common.Tools.csproj" />
    <ProjectReference Include="..\OpenBreed.Common.Game.Wecs\OpenBreed.Common.Game.Wecs.csproj" />
    <ProjectReference Include="..\OpenBreed.Common.Windows\OpenBreed.Common.Windows.csproj" />
    <ProjectReference Include="..\OpenBreed.Common\OpenBreed.Common.csproj" />
    <ProjectReference Include="..\OpenBreed.Database.Interface\OpenBreed.Database.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Database.Xml\OpenBreed.Database.Xml.csproj" />
    <ProjectReference Include="..\OpenBreed.Model\OpenBreed.Model.csproj" />
    <ProjectReference Include="..\OpenBreed.Animation.Generic\OpenBreed.Animation.Generic.csproj" />
    <ProjectReference Include="..\OpenBreed.Animation.Interface\OpenBreed.Animation.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Audio.Interface\OpenBreed.Audio.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Audio.OpenAL\OpenBreed.Audio.OpenAL.csproj" />
    <ProjectReference Include="..\OpenBreed.Core\OpenBreed.Core.csproj" />
    <ProjectReference Include="..\OpenBreed.Fsm\OpenBreed.Fsm.csproj" />
    <ProjectReference Include="..\OpenBreed.Input.Generic\OpenBreed.Input.Generic.csproj" />
    <ProjectReference Include="..\OpenBreed.Input.Interface\OpenBreed.Input.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Physics.Generic\OpenBreed.Physics.Generic.csproj" />
    <ProjectReference Include="..\OpenBreed.Physics.Interface\OpenBreed.Physics.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Rendering.Abstractions\OpenBreed.Rendering.Abstractions.csproj" />
    <ProjectReference Include="..\OpenBreed.Rendering.OpenGL\OpenBreed.Rendering.OpenGL.csproj" />
    <ProjectReference Include="..\OpenBreed.Scripting.Interface\OpenBreed.Scripting.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Scripting.Lua\OpenBreed.Scripting.Lua.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Animation.Components\OpenBreed.Wecs.Animation.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Audio.Components\OpenBreed.Wecs.Audio.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Core.Components\OpenBreed.Wecs.Core.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Control.Components\OpenBreed.Wecs.Control.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Gui.Components\OpenBreed.Wecs.Gui.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Physics.Components\OpenBreed.Wecs.Physics.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Rendering.Components\OpenBreed.Wecs.Rendering.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Scripting.Components\OpenBreed.Wecs.Scripting.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Animation.Systems\OpenBreed.Wecs.Animation.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Audio.Systems\OpenBreed.Wecs.Audio.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Control.Systems\OpenBreed.Wecs.Control.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Core.Systems\OpenBreed.Wecs.Core.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Gui.Systems\OpenBreed.Wecs.Gui.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Physics.Systems\OpenBreed.Wecs.Physics.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Rendering.Systems\OpenBreed.Wecs.Rendering.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Scripting.Systems\OpenBreed.Wecs.Scripting.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs\OpenBreed.Wecs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Factories\" />
    <Folder Include="Systems\Screen\" />
    <Folder Include="Worlds\" />
  </ItemGroup>

</Project>
