Templates.Entities.Turret = {
    ClassComponent = { "Turret" },
    TimerComponent = {},
    FsmComponent = { { "Turret.Rotation", "Idle" } },
    AnimationComponent = {
        Speed = 10.0,
        Loop = true},
    PositionComponent = { 0, 0 },
    ThrustComponent = { 0, 0 },
    VelocityComponent = { 0, 0 },
    AngularPositionComponent = { 0 },
    BodyComponent = {
        CofFactor = 1.0,
        CorFactor = 0.0,
        Type = "Static",
		Fixtures = { "Fixtures/Turret" } },
	MotionComponent = {},
	SpriteComponent = {
		AtlasId = "Atlases/Sprites/Turret",
        Order = 100.0},
	TextComponent = {
		Text = "Turret",
		Offset = { 0, 32 },
		Color = { 255, 255, 255, 255 },
		FontId = { "Arial", 9 },
        Order = 0.0}
}