<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\add_24dp.png" />
    <None Remove="Icons\center_focus_24dp.png" />
    <None Remove="Icons\close_small_24dp.png" />
    <None Remove="Icons\content_copy_24dp.png" />
    <None Remove="Icons\done_24dp.png" />
    <None Remove="Icons\fast_forward_24dp.png" />
    <None Remove="Icons\fast_rewind_24dp.png" />
    <None Remove="Icons\pause_circle_24dp.png" />
    <None Remove="Icons\play_circle_24dp.png" />
    <None Remove="Icons\point_add_24dp.png" />
    <None Remove="Icons\point_select_24dp.png" />
    <None Remove="Icons\remove_24dp.png" />
    <None Remove="Icons\skip_next_24dp.png" />
    <None Remove="Icons\skip_previous_24dp.png" />
    <None Remove="Icons\stop_circle_24dp.png" />
    <None Remove="Icons\undo_24dp.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Editor.VM\OpenBreed.Editor.VM.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Animations\AnimationEditorCtrl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Converters\ColorToBrushConverter.cs">
      <Generator></Generator>
    </Compile>
    <Compile Update="Images\ImageFromAcbmEditorCtrl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Options\EditorOptionsAbta.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Options\EditorOptionsAbse.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="TileStamps\TileStampEditorCtrl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Tiles\TileSetFromAcbmEditorCtrl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="OpenTK.GLWpfControl" Version="4.3.6" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\add_24dp.png" />
    <Resource Include="Icons\center_focus_24dp.png" />
    <Resource Include="Icons\close_small_24dp.png" />
    <Resource Include="Icons\content_copy_24dp.png" />
    <Resource Include="Icons\done_24dp.png" />
    <Resource Include="Icons\fast_forward_24dp.png" />
    <Resource Include="Icons\fast_rewind_24dp.png" />
    <Resource Include="Icons\pause_circle_24dp.png" />
    <Resource Include="Icons\play_circle_24dp.png" />
    <Resource Include="Icons\point_add_24dp.png" />
    <Resource Include="Icons\point_select_24dp.png" />
    <Resource Include="Icons\remove_24dp.png" />
    <Resource Include="Icons\skip_next_24dp.png" />
    <Resource Include="Icons\skip_previous_24dp.png" />
    <Resource Include="Icons\stop_circle_24dp.png" />
    <Resource Include="Icons\undo_24dp.png" />
  </ItemGroup>

</Project>
