<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Helpers\**" />
	  <EmbeddedResource Remove="Helpers\**" />
	  <None Remove="Helpers\**" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="5.0.0-pre.16" />
	<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Common\OpenBreed.Common.csproj" />
    <ProjectReference Include="..\OpenBreed.Physics.Abstractions\OpenBreed.Physics.Abstractions.csproj" />
  </ItemGroup>

</Project>
