<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Entities\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Entities\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Animation.Generic\OpenBreed.Animation.Generic.csproj" />
    <ProjectReference Include="..\OpenBreed.Common.Game\OpenBreed.Common.Game.csproj" />
    <ProjectReference Include="..\OpenBreed.Physics.Interface\OpenBreed.Physics.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Control.Components\OpenBreed.Wecs.Control.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Audio.Systems\OpenBreed.Wecs.Audio.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Control.Systems\OpenBreed.Wecs.Control.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Core.Systems\OpenBreed.Wecs.Core.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Gui.Systems\OpenBreed.Wecs.Gui.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Physics.Systems\OpenBreed.Wecs.Physics.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Rendering.Systems\OpenBreed.Wecs.Rendering.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Scripting.Systems\OpenBreed.Wecs.Scripting.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs\OpenBreed.Wecs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Systems\Turret\" />
  </ItemGroup>

</Project>
