<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPFArchive" Version="1.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Common.Interface\OpenBreed.Common.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Database.Interface\OpenBreed.Database.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Model\OpenBreed.Model.csproj" />
    <ProjectReference Include="..\OpenBreed.Reader.Legacy\OpenBreed.Reader.Legacy.csproj" />
    <ProjectReference Include="..\OpenBreed.Writer.Legacy\OpenBreed.Writer.Legacy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Attributes\" />
  </ItemGroup>

</Project>
