<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Audio.Interface\OpenBreed.Audio.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Audio.Components\OpenBreed.Wecs.Audio.Components.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Core.Systems\OpenBreed.Wecs.Core.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs\OpenBreed.Wecs.csproj" />
  </ItemGroup>

</Project>
