<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Common.Game.Wecs\OpenBreed.Common.Game.Wecs.csproj" />
    <ProjectReference Include="..\OpenBreed.Core.Abstractions\OpenBreed.Core.Abstractions.csproj" />
    <ProjectReference Include="..\OpenBreed.Gui.Abstractions\OpenBreed.Gui.Abstractions.csproj" />
    <ProjectReference Include="..\OpenBreed.Gui\OpenBreed.Gui.csproj" />
    <ProjectReference Include="..\OpenBreed.Rendering.Abstractions\OpenBreed.Rendering.Abstractions.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs\OpenBreed.Wecs.csproj" />
  </ItemGroup>

</Project>
