<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="Systems\EventSystemManager.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0" />
	</ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\OpenBreed.Wecs.Abstractions\OpenBreed.Wecs.Abstractions.csproj" />
    <ProjectReference Include="..\OpenBreed.Common\OpenBreed.Common.csproj" />
    <ProjectReference Include="..\OpenBreed.Core\OpenBreed.Core.csproj" />
    <ProjectReference Include="..\OpenBreed.Input.Interface\OpenBreed.Input.Interface.csproj" />
    <ProjectReference Include="..\OpenBreed.Rendering.Abstractions\OpenBreed.Rendering.Abstractions.csproj" />
    <ProjectReference Include="..\OpenBreed.Scripting.Interface\OpenBreed.Scripting.Interface.csproj" />
  </ItemGroup>

</Project>
