<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Pathfinding.Abstractions\OpenBreed.Pathfinding.Abstractions.csproj" />
  </ItemGroup>

</Project>
