<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Audio.Abstractions\OpenBreed.Audio.Abstractions.csproj" />
    <ProjectReference Include="..\OpenBreed.Audio.LibOpenMpt\OpenBreed.Audio.LibOpenMpt.csproj" />
    <ProjectReference Include="..\OpenBreed.Audio.OpenAL\OpenBreed.Audio.OpenAL.csproj" />
    <ProjectReference Include="..\OpenBreed.Core\OpenBreed.Core.csproj" />
    <ProjectReference Include="..\OpenBreed.Input.Generic\OpenBreed.Input.Generic.csproj" />
    <ProjectReference Include="..\OpenBreed.Model\OpenBreed.Model.csproj" />
    <ProjectReference Include="..\OpenBreed.Physics.Generic\OpenBreed.Physics.Generic.csproj" />
    <ProjectReference Include="..\OpenBreed.Physics.Abstractions\OpenBreed.Physics.Abstractions.csproj" />
    <ProjectReference Include="..\OpenBreed.Rendering.Abstractions\OpenBreed.Rendering.Abstractions.csproj" />
    <ProjectReference Include="..\OpenBreed.Rendering.Common\OpenBreed.Rendering.Common.csproj" />
    <ProjectReference Include="..\OpenBreed.Rendering.OpenGL\OpenBreed.Rendering.OpenGL.csproj" />
    <ProjectReference Include="..\OpenBreed.Scripting.Lua\OpenBreed.Scripting.Lua.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Control.Systems\OpenBreed.Wecs.Control.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Core.Systems\OpenBreed.Wecs.Core.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs.Rendering.Systems\OpenBreed.Wecs.Rendering.Systems.csproj" />
    <ProjectReference Include="..\OpenBreed.Wecs\OpenBreed.Wecs.csproj" />
  </ItemGroup>

</Project>
