<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLua" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBreed.Common\OpenBreed.Common.csproj" />
    <ProjectReference Include="..\OpenBreed.Scripting.Abstractions\OpenBreed.Scripting.Abstractions.csproj" />
  </ItemGroup>

</Project>
