Templates.Entities.Projectile = {
    FsmComponent = { { "Projectile" , "Fired"} },
    AnimationComponent = {
        Speed = 10.0,
        Loop = true},
    PositionComponent = { 0, 0 },
    ThrustComponent = { 0, 0 },
    VelocityComponent = { 0, 0 },
    BodyComponent = {
        CofFactor = 0.0,
        CorFactor = 1.0,
        Type = "Dynamic",
		Fixtures = { "Fixtures/Projectile" } },
	SpriteComponent = {
		AtlasId = "Atlases/Sprites/Projectiles/Laser",
        Order = 0.0,
        Width = 16.0,
        Height = 16.0},
	TextComponent = {
		Text = "Bullet",
		Offset = { -10, 10 },
		Color = { 255, 255, 255, 255 },
		FontId = { "Arial", 9 },
        Order = 0.0}
}